### ISSUE TITLE
Usage of EMA

### ISSUE THREAD

**Issue by dxli94** [YaYaB/finetune-diffusion#1]
Hello @YaYaB ,

Thanks for the nice implementation!

I notice the [official finetuning script](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/README.md#hardware) activates --use-ema. Do you also use EMA?

Thanks!

**Comment by YaYaB** [comment]
Thanks @dxli94  :)
You can use ema by specifying it in the script with the following flag ``--use_ema``. I did not use it because I had gpu issues with it (it consumed too many memory)

**Comment by dxli94** [comment]
Thanks for the prompt response. Regards.
