### ISSUE TITLE
What's the best BLIP checkpoint

### ISSUE THREAD

**Issue by zetyquickly** [YaYaB/finetune-diffusion#2]
Hello,

Have you experimented with different BLIP models? What's the best choice was in your Magic/OnePiece case?

**Comment by YaYaB** [comment]
Hello !
I honestly did not experimented much with BLIP models and used the one lambdalabs used in their work. It corresponds to the [BLIP w/ ViT-B and CapFilt-L](https://github.com/YaYaB/finetune-diffusion/blob/main/caption.py#L39). Using [BLIP w/ ViT-L on CoCo captioning](https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth) might give different results. This is what they use in their demo on HuggingFace's space https://huggingface.co/spaces/Salesforce/BLIP

**Comment by zetyquickly** [comment]
I see. Thank you, I think it's up to experiment, which BLIP model to choose.

Btw, I haven't found info which BLIP model lambdalabs used exactly. 
Tried all image-captioning models and got the following results on pokemon dataset.

<img width="741" alt="Screen Shot 2022-10-27 at 9 06 00 AM" src="https://user-images.githubusercontent.com/25350960/198341899-d166eab0-685e-4474-aa45-8c63783d6129.png">

none of them exactly gives "a red and white ball with an angry look on its face"

**Comment by YaYaB** [comment]
Indeed they just say to use https://github.com/salesforce/BLIP.
Did you try to run the generation using the same model several times? You should not get the same caption if you use *nucleus_sampling*. Maybe this is what they did? You could ask them in their repository
